// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMJk0axgc-1PUOeix1b67FMQEZieRQ4I',
    appId: '1:745919180850:android:f5e4ce02653a5bdb7ccc2b',
    messagingSenderId: '745919180850',
    projectId: 'fyp-iot-project-48759',
    databaseURL: 'https://fyp-iot-project-48759-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-iot-project-48759.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQY0-9Qw4puGVGKzqLGi5tar4kpH1da0',
    appId: '1:745919180850:ios:1b96f0ff7a9355597ccc2b',
    messagingSenderId: '745919180850',
    projectId: 'fyp-iot-project-48759',
    databaseURL: 'https://fyp-iot-project-48759-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-iot-project-48759.firebasestorage.app',
    androidClientId: '745919180850-v1nmaqq2io00noi6f9j3dlk0gb7mbdak.apps.googleusercontent.com',
    iosClientId: '745919180850-opmfa950aqlf11eg4782iefinkhtn4tm.apps.googleusercontent.com',
    iosBundleId: 'com.fyp.airqualitymonitor.fypIotProject',
  );
}
